#!/usr/bin/env python3
"""
parse-insights.py — Parse /insights HTML report into structured JSON.

Reads ~/.claude/usage-data/report.html (generated by Claude Code's /insights
command), plus supporting facets/*.json and session-meta/*.json files, and
writes structured content blocks to docs/insights-parsed.json.

Python 3.10+, stdlib only.
"""

from __future__ import annotations

import json
import re
import sys
from datetime import datetime, timezone
from html.parser import HTMLParser
from pathlib import Path

# Resolve project root (4 levels up from this script)
SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parents[3]  # .claude/skills/refresh-guidelines/scripts/ -> root
OUTPUT_FILE = PROJECT_ROOT / "docs" / "insights-parsed.json"

# Default /insights data location
DEFAULT_USAGE_DATA_DIR = Path.home() / ".claude" / "usage-data"

# Staleness threshold in days
STALENESS_DAYS = 7


# ---------------------------------------------------------------------------
# Report discovery
# ---------------------------------------------------------------------------

def find_report(
    report_dir: Path | None = None,
) -> tuple[Path | None, int]:
    """Locate report.html and calculate staleness in days.

    Returns (path, staleness_days). Path is None if report doesn't exist.
    """
    data_dir = report_dir or DEFAULT_USAGE_DATA_DIR
    report_path = data_dir / "report.html"

    if not report_path.exists():
        return None, -1

    mtime = datetime.fromtimestamp(report_path.stat().st_mtime, tz=timezone.utc)
    now = datetime.now(timezone.utc)
    staleness = (now - mtime).days

    return report_path, staleness


# ---------------------------------------------------------------------------
# HTML parsing
# ---------------------------------------------------------------------------

class InsightsHTMLParser(HTMLParser):
    """Extract structured sections from /insights report.html.

    Uses a state-machine approach tracking current section (via <h2 id=...>)
    and current element class to extract title/description pairs from cards.
    """

    # Map section IDs to our internal section names
    SECTION_MAP = {
        "section-wins": "wins",
        "section-friction": "friction",
        "section-features": "features",
        "section-patterns": "patterns",
        "section-horizon": "horizon",
        "section-usage": "usage",
        "section-work": "work",
    }

    # Card classes we extract from, mapped to their title/desc child classes
    CARD_TYPES = {
        "big-win": ("big-win-title", "big-win-desc"),
        "friction-category": ("friction-title", "friction-desc"),
        "feature-card": ("feature-title", "feature-why"),
        "pattern-card": ("pattern-title", "pattern-detail"),
        "horizon-card": ("horizon-title", "horizon-possible"),
    }

    def __init__(self) -> None:
        super().__init__()
        self._section: str = ""  # Current section name
        self._in_card: str = ""  # Current card class (e.g., "big-win")
        self._in_element: str = ""  # Current child element class
        self._text_buf: list[str] = []
        self._card_depth: int = 0  # Div nesting depth within current card

        # Collected data
        self.sections: dict[str, list[dict]] = {
            "wins": [],
            "friction": [],
            "features": [],
            "patterns": [],
            "horizon": [],
            "usage": [],
        }
        self.claude_md_recs: list[dict] = []
        self.stats: dict[str, str] = {}

        # Temp storage for current card being parsed
        self._card_title: str = ""
        self._card_desc: str = ""
        self._card_evidence: str = ""  # For friction examples, cmd-why, etc.

        # CLAUDE.md recommendation parsing
        self._in_cmd_item: bool = False
        self._current_cmd_text: str = ""
        self._current_cmd_why: str = ""
        self._in_cmd_why: bool = False
        self._in_cmd_code: bool = False

        # Narrative parsing
        self._in_narrative: bool = False
        self._in_key_insight: bool = False
        self._narrative_text: list[str] = []

        # Stats parsing
        self._in_stat: bool = False
        self._in_stat_value: bool = False
        self._in_stat_label: bool = False
        self._stat_value: str = ""

        # Friction examples
        self._in_friction_examples: bool = False
        self._friction_examples: list[str] = []

        # Feature one-liner
        self._in_feature_oneliner: bool = False
        self._feature_oneliner: str = ""

        # Pattern summary
        self._in_pattern_summary: bool = False
        self._pattern_summary: str = ""

        # Horizon tip
        self._in_horizon_tip: bool = False
        self._horizon_tip: str = ""

        # Subtitle (contains session/date info)
        self._in_subtitle: bool = False
        self.subtitle: str = ""

    def _get_class(self, attrs: list[tuple[str, str | None]]) -> str:
        """Extract class attribute from tag attrs."""
        for name, value in attrs:
            if name == "class" and value:
                return value
        return ""

    def _get_attr(self, attrs: list[tuple[str, str | None]], attr_name: str) -> str:
        """Extract a specific attribute value."""
        for name, value in attrs:
            if name == attr_name and value:
                return value
        return ""

    def _get_id(self, attrs: list[tuple[str, str | None]]) -> str:
        """Extract id attribute from tag attrs."""
        for name, value in attrs:
            if name == "id" and value:
                return value
        return ""

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        cls = self._get_class(attrs)
        tag_id = self._get_id(attrs)

        # Track sections via h2 with known IDs
        if tag == "h2" and tag_id in self.SECTION_MAP:
            self._section = self.SECTION_MAP[tag_id]
            return

        # Subtitle
        if cls == "subtitle":
            self._in_subtitle = True
            return

        # Stats
        if cls == "stat":
            self._in_stat = True
        elif cls == "stat-value":
            self._in_stat_value = True
        elif cls == "stat-label":
            self._in_stat_label = True

        # Card detection
        for card_cls in self.CARD_TYPES:
            if card_cls in cls.split():
                self._in_card = card_cls
                self._card_depth = 1  # We're inside the card's opening div
                self._card_title = ""
                self._card_desc = ""
                self._card_evidence = ""
                self._friction_examples = []
                self._feature_oneliner = ""
                self._pattern_summary = ""
                self._horizon_tip = ""
                return

        # Track div nesting within a card
        if self._in_card and tag == "div":
            self._card_depth += 1

        # Card child elements
        if self._in_card:
            title_cls, desc_cls = self.CARD_TYPES.get(self._in_card, ("", ""))
            if title_cls in cls.split():
                self._in_element = "title"
                self._text_buf = []
            elif desc_cls in cls.split():
                self._in_element = "desc"
                self._text_buf = []
            elif "friction-examples" in cls.split():
                self._in_friction_examples = True
                self._friction_examples = []
            elif "feature-oneliner" in cls.split():
                self._in_feature_oneliner = True
                self._text_buf = []
            elif "pattern-summary" in cls.split():
                self._in_pattern_summary = True
                self._text_buf = []
            elif "horizon-tip" in cls.split():
                self._in_horizon_tip = True
                self._text_buf = []

        # Friction example list items
        if tag == "li" and self._in_friction_examples:
            self._text_buf = []
            self._in_element = "friction-li"

        # CLAUDE.md recommendation items
        if "claude-md-item" in cls.split():
            self._in_cmd_item = True
            self._current_cmd_text = ""
            self._current_cmd_why = ""

        if self._in_cmd_item:
            # Checkbox with data-text attribute
            if tag == "input" and self._get_class(attrs) == "cmd-checkbox":
                self._current_cmd_text = self._get_attr(attrs, "data-text")
            elif "cmd-code" in cls.split():
                self._in_cmd_code = True
                self._text_buf = []
            elif "cmd-why" in cls.split():
                self._in_cmd_why = True
                self._text_buf = []

        # Narrative section
        if self._section == "usage":
            if "narrative" in cls.split():
                self._in_narrative = True
                self._narrative_text = []
            elif "key-insight" in cls.split():
                self._in_key_insight = True
                self._text_buf = []
            elif tag == "p" and self._in_narrative:
                self._text_buf = []
                self._in_element = "narrative-p"

    def handle_endtag(self, tag: str) -> None:
        cls_ctx = self._in_element

        # End of card child elements
        if cls_ctx == "title" and tag in ("div", "span"):
            self._card_title = " ".join(self._text_buf).strip()
            self._in_element = ""
        elif cls_ctx == "desc" and tag in ("div", "span", "p"):
            self._card_desc = " ".join(self._text_buf).strip()
            self._in_element = ""
        elif cls_ctx == "friction-li" and tag == "li":
            self._friction_examples.append(" ".join(self._text_buf).strip())
            self._in_element = ""

        # Feature one-liner
        if self._in_feature_oneliner and tag == "div":
            self._feature_oneliner = " ".join(self._text_buf).strip()
            self._in_feature_oneliner = False

        # Pattern summary
        if self._in_pattern_summary and tag == "div":
            self._pattern_summary = " ".join(self._text_buf).strip()
            self._in_pattern_summary = False

        # Horizon tip
        if self._in_horizon_tip and tag == "div":
            self._horizon_tip = " ".join(self._text_buf).strip()
            self._in_horizon_tip = False

        # Friction examples list
        if self._in_friction_examples and tag == "ul":
            self._in_friction_examples = False

        # Track card div depth
        if self._in_card and tag == "div":
            self._card_depth -= 1

        # End of card (outer div closed)
        if self._in_card and tag == "div" and self._card_depth <= 0:
            card_type = self._in_card
            if self._card_title:
                entry: dict = {
                    "title": self._card_title,
                    "description": self._card_desc,
                }
                if self._friction_examples:
                    entry["evidence"] = " | ".join(self._friction_examples)
                if self._feature_oneliner:
                    entry["one_liner"] = self._feature_oneliner
                if self._pattern_summary:
                    entry["summary"] = self._pattern_summary
                if self._horizon_tip:
                    entry["tip"] = self._horizon_tip

                section_name = {
                    "big-win": "wins",
                    "friction-category": "friction",
                    "feature-card": "features",
                    "pattern-card": "patterns",
                    "horizon-card": "horizon",
                }.get(card_type, "")

                if section_name and section_name in self.sections:
                    self.sections[section_name].append(entry)

                self._in_card = ""
                self._in_element = ""

        # CLAUDE.md recommendation items
        if self._in_cmd_code and tag in ("code",):
            if not self._current_cmd_text:
                self._current_cmd_text = " ".join(self._text_buf).strip()
            self._in_cmd_code = False
        if self._in_cmd_why and tag == "div":
            self._current_cmd_why = " ".join(self._text_buf).strip()
            self._in_cmd_why = False
        if self._in_cmd_item and tag == "div":
            if self._current_cmd_text:
                self.claude_md_recs.append({
                    "text": self._current_cmd_text,
                    "evidence": self._current_cmd_why,
                })
            self._in_cmd_item = False

        # Narrative
        if cls_ctx == "narrative-p" and tag == "p":
            self._narrative_text.append(" ".join(self._text_buf).strip())
            self._in_element = ""
        if self._in_key_insight and tag == "div":
            insight_text = " ".join(self._text_buf).strip()
            if insight_text:
                self._narrative_text.append(f"[Key insight] {insight_text}")
            self._in_key_insight = False
        if self._in_narrative and tag == "div":
            if self._narrative_text:
                for text in self._narrative_text:
                    if text:
                        self.sections["usage"].append({
                            "title": "Usage Narrative",
                            "description": text,
                        })
            self._in_narrative = False

        # Subtitle
        if self._in_subtitle and tag == "p":
            self._in_subtitle = False

        # Stats
        if self._in_stat_value and tag == "div":
            self._in_stat_value = False
        if self._in_stat_label and tag == "div":
            self._in_stat_label = False
        if self._in_stat and tag == "div":
            self._in_stat = False

    def handle_data(self, data: str) -> None:
        text = data.strip()
        if not text:
            return

        # Subtitle
        if self._in_subtitle:
            self.subtitle += data

        # Stats
        if self._in_stat_value:
            self._stat_value = text
        elif self._in_stat_label:
            self.stats[text] = self._stat_value

        # Buffer text for current element
        if self._in_element or self._in_cmd_why or self._in_cmd_code:
            self._text_buf.append(text)

        if self._in_feature_oneliner:
            self._text_buf.append(text)
        if self._in_pattern_summary:
            self._text_buf.append(text)
        if self._in_horizon_tip:
            self._text_buf.append(text)

        # Narrative text
        if self._in_element == "narrative-p":
            pass  # Already handled by _text_buf
        elif self._in_key_insight:
            self._text_buf.append(text)


# ---------------------------------------------------------------------------
# Facets and session-meta parsing
# ---------------------------------------------------------------------------

def parse_facets(facets_dir: Path) -> dict:
    """Aggregate data from facets/*.json files.

    Returns dict with friction_types, session_types, outcomes, summaries.
    """
    result: dict = {
        "friction_types": {},
        "session_types": {},
        "outcomes": {},
        "total_sessions": 0,
        "summaries": [],
    }

    if not facets_dir.exists():
        return result

    for f in sorted(facets_dir.glob("*.json")):
        try:
            data = json.loads(f.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            continue

        result["total_sessions"] += 1

        # Friction types
        for ftype, count in data.get("friction_counts", {}).items():
            result["friction_types"][ftype] = (
                result["friction_types"].get(ftype, 0) + count
            )

        # Session types
        stype = data.get("session_type", "unknown")
        result["session_types"][stype] = result["session_types"].get(stype, 0) + 1

        # Outcomes
        outcome = data.get("outcome", "unknown")
        result["outcomes"][outcome] = result["outcomes"].get(outcome, 0) + 1

        # Brief summaries
        summary = data.get("brief_summary", "")
        if summary:
            result["summaries"].append(summary)

    return result


def parse_session_meta(meta_dir: Path) -> dict:
    """Aggregate data from session-meta/*.json files.

    Returns dict with tool_counts, languages, session_count, date_range.
    """
    result: dict = {
        "total_sessions": 0,
        "total_messages": 0,
        "tool_counts": {},
        "languages": {},
        "date_range_start": "",
        "date_range_end": "",
    }

    if not meta_dir.exists():
        return result

    dates: list[str] = []

    for f in sorted(meta_dir.glob("*.json")):
        try:
            data = json.loads(f.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            continue

        result["total_sessions"] += 1
        result["total_messages"] += data.get("user_message_count", 0)
        result["total_messages"] += data.get("assistant_message_count", 0)

        # Tool counts
        for tool, count in data.get("tool_counts", {}).items():
            result["tool_counts"][tool] = result["tool_counts"].get(tool, 0) + count

        # Languages
        for lang, count in data.get("languages", {}).items():
            result["languages"][lang] = result["languages"].get(lang, 0) + count

        # Date tracking
        start_time = data.get("start_time", "")
        if start_time:
            dates.append(start_time[:10])  # YYYY-MM-DD

    if dates:
        dates.sort()
        result["date_range_start"] = dates[0]
        result["date_range_end"] = dates[-1]

    return result


# ---------------------------------------------------------------------------
# Content block builders
# ---------------------------------------------------------------------------

def _build_entries(
    sections: dict[str, list[dict]],
    claude_md_recs: list[dict],
) -> list[dict]:
    """Convert parsed HTML sections into output entries."""
    entries: list[dict] = []

    # 1. CLAUDE.md Recommendations (highest internal priority)
    if claude_md_recs:
        blocks = []
        for rec in claude_md_recs:
            blocks.append({
                "theme": "behavioral",
                "heading": _extract_heading(rec["text"]),
                "text": rec["text"],
                "evidence": rec.get("evidence", ""),
            })
        entries.append({
            "source_id": "insights-claudemd-rec",
            "source_name": "/insights CLAUDE.md Recommendations",
            "tier": "insights",
            "themes": ["content", "behavioral"],
            "content_blocks": blocks,
        })

    # 2. Friction points
    if sections.get("friction"):
        blocks = []
        for item in sections["friction"]:
            blocks.append({
                "theme": "anti-patterns",
                "heading": item["title"],
                "text": item["description"],
                "evidence": item.get("evidence", ""),
            })
        entries.append({
            "source_id": "insights-friction",
            "source_name": "/insights Friction Points",
            "tier": "insights",
            "themes": ["anti-patterns", "behavioral"],
            "content_blocks": blocks,
        })

    # 3. Working workflows (wins)
    if sections.get("wins"):
        blocks = []
        for item in sections["wins"]:
            blocks.append({
                "theme": "behavioral",
                "heading": item["title"],
                "text": item["description"],
            })
        entries.append({
            "source_id": "insights-wins",
            "source_name": "/insights Working Workflows",
            "tier": "insights",
            "themes": ["behavioral"],
            "content_blocks": blocks,
        })

    # 4. Feature recommendations
    if sections.get("features"):
        blocks = []
        for item in sections["features"]:
            text = item["description"]
            if item.get("one_liner"):
                text = f"{item['one_liner']}\n\n{text}"
            blocks.append({
                "theme": "integration",
                "heading": item["title"],
                "text": text,
            })
        entries.append({
            "source_id": "insights-features",
            "source_name": "/insights Feature Recommendations",
            "tier": "insights",
            "themes": ["integration"],
            "content_blocks": blocks,
        })

    # 5. Usage patterns
    if sections.get("patterns"):
        blocks = []
        for item in sections["patterns"]:
            text = item["description"]
            if item.get("summary"):
                text = f"{item['summary']}\n\n{text}"
            blocks.append({
                "theme": "behavioral",
                "heading": item["title"],
                "text": text,
            })
        entries.append({
            "source_id": "insights-patterns",
            "source_name": "/insights Usage Patterns",
            "tier": "insights",
            "themes": ["behavioral", "maintenance"],
            "content_blocks": blocks,
        })

    # 6. Future workflows (horizon)
    if sections.get("horizon"):
        blocks = []
        for item in sections["horizon"]:
            text = item["description"]
            if item.get("tip"):
                text += f"\n\nGetting started: {item['tip']}"
            blocks.append({
                "theme": "maintenance",
                "heading": item["title"],
                "text": text,
            })
        entries.append({
            "source_id": "insights-horizon",
            "source_name": "/insights Future Workflows",
            "tier": "insights",
            "themes": ["maintenance"],
            "content_blocks": blocks,
        })

    # 7. Usage narrative
    if sections.get("usage"):
        blocks = []
        for item in sections["usage"]:
            blocks.append({
                "theme": "behavioral",
                "heading": item["title"],
                "text": item["description"],
            })
        entries.append({
            "source_id": "insights-usage",
            "source_name": "/insights Usage Narrative",
            "tier": "insights",
            "themes": ["behavioral"],
            "content_blocks": blocks,
        })

    return entries


def _extract_heading(text: str) -> str:
    """Extract a short heading from a CLAUDE.md recommendation text."""
    # Try to get the "Add under ..." prefix
    match = re.match(r"Add under (?:a new |the )?(##?\s*\S.*?)(?:\n|$)", text)
    if match:
        return match.group(1).strip()
    # Fallback: first ~60 chars
    first_line = text.split("\n")[0]
    if len(first_line) > 60:
        return first_line[:57] + "..."
    return first_line


def _parse_subtitle(subtitle: str) -> tuple[int, str]:
    """Extract session count and date range from subtitle text.

    Example: '134 messages across 19 sessions (24 total) | 2026-01-16 to 2026-02-10'
    Returns: (19, '2026-01-16 to 2026-02-10')
    """
    sessions = 0
    date_range = ""

    session_match = re.search(r"(\d+)\s+sessions", subtitle)
    if session_match:
        sessions = int(session_match.group(1))

    date_match = re.search(r"(\d{4}-\d{2}-\d{2}\s+to\s+\d{4}-\d{2}-\d{2})", subtitle)
    if date_match:
        date_range = date_match.group(1)

    return sessions, date_range


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main(report_dir: Path | None = None) -> int:
    """Parse /insights data and write structured output.

    Args:
        report_dir: Override for ~/.claude/usage-data/ (for testing).

    Returns 0 on success (including missing report), 1 on fatal error.
    """
    data_dir = report_dir or DEFAULT_USAGE_DATA_DIR

    print(
        f"parse-insights.py — {datetime.now(timezone.utc).isoformat()}",
        file=sys.stderr,
    )

    # Find report
    report_path, staleness_days = find_report(data_dir)

    if report_path is None:
        print(
            f"WARNING: No /insights report found at {data_dir / 'report.html'}",
            file=sys.stderr,
        )
        print("Producing minimal output — web sources only.", file=sys.stderr)
        _write_minimal_output(data_dir)
        return 0

    is_stale = staleness_days > STALENESS_DAYS
    if is_stale:
        print(
            f"WARNING: /insights report is {staleness_days} days old (stale > {STALENESS_DAYS} days).",
            file=sys.stderr,
        )
        print(
            "Consider running /insights first for fresher data.",
            file=sys.stderr,
        )

    print(f"Report: {report_path} (age: {staleness_days} days)", file=sys.stderr)

    # Parse HTML report
    try:
        html_content = report_path.read_text(encoding="utf-8")
    except OSError as e:
        print(f"ERROR: Cannot read report: {e}", file=sys.stderr)
        _write_minimal_output(data_dir)
        return 0

    parser = InsightsHTMLParser()
    try:
        parser.feed(html_content)
    except Exception as e:
        print(f"WARNING: HTML parsing error: {e}", file=sys.stderr)

    # Parse supporting JSON
    facets_dir = data_dir / "facets"
    meta_dir = data_dir / "session-meta"

    facets_data = parse_facets(facets_dir)
    meta_data = parse_session_meta(meta_dir)

    # Build output entries
    entries = _build_entries(parser.sections, parser.claude_md_recs)

    # Extract metadata from subtitle
    sessions_from_subtitle, date_range = _parse_subtitle(parser.subtitle)

    # Report modification time
    report_mtime = datetime.fromtimestamp(
        report_path.stat().st_mtime, tz=timezone.utc
    ).isoformat()

    # Compose output
    output = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "report_path": str(report_path),
        "report_modified_at": report_mtime,
        "staleness_days": staleness_days,
        "is_stale": is_stale,
        "sessions_analyzed": sessions_from_subtitle or meta_data["total_sessions"],
        "date_range": date_range or (
            f"{meta_data['date_range_start']} to {meta_data['date_range_end']}"
            if meta_data["date_range_start"]
            else ""
        ),
        "entries": entries,
        "session_stats": {
            "total_sessions": meta_data["total_sessions"],
            "total_messages": meta_data["total_messages"],
            "top_tools": dict(
                sorted(
                    meta_data["tool_counts"].items(),
                    key=lambda x: x[1],
                    reverse=True,
                )[:6]
            ),
            "primary_languages": dict(
                sorted(
                    meta_data["languages"].items(),
                    key=lambda x: x[1],
                    reverse=True,
                )[:6]
            ),
            "outcome_distribution": facets_data["outcomes"],
        },
    }

    # Write output
    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_FILE.write_text(
        json.dumps(output, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )

    # Summary
    total_blocks = sum(len(e["content_blocks"]) for e in entries)
    print("\n--- Summary ---", file=sys.stderr)
    print(f"Entries: {len(entries)} sections, {total_blocks} content blocks", file=sys.stderr)
    print(f"Sessions analyzed: {output['sessions_analyzed']}", file=sys.stderr)
    print(f"Date range: {output['date_range']}", file=sys.stderr)
    print(f"Stale: {is_stale} ({staleness_days} days)", file=sys.stderr)
    print(f"Output: {OUTPUT_FILE}", file=sys.stderr)

    return 0


def _write_minimal_output(data_dir: Path) -> None:
    """Write minimal output JSON when no report is available."""
    output = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "report_path": str(data_dir / "report.html"),
        "report_modified_at": "",
        "staleness_days": -1,
        "is_stale": True,
        "sessions_analyzed": 0,
        "date_range": "",
        "entries": [],
        "session_stats": {
            "total_sessions": 0,
            "total_messages": 0,
            "top_tools": {},
            "primary_languages": {},
            "outcome_distribution": {},
        },
    }
    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_FILE.write_text(
        json.dumps(output, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    sys.exit(main())
